# Generated by Django 5.1 on 2024-09-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('ticket_type', models.CharField(choices=[('regular', 'Regular - 50 Cedis'), ('double', 'Double - 70 Cedis')], max_length=7)),
                ('unique_code', models.CharField(blank=True, max_length=10, unique=True)),
            ],
        ),
    ]
