# Generated by Django 5.1 on 2024-09-01 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='data',
        ),
    ]
